name: Publish Docker image
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - main
      - 'v\d+'
      - 'v\d+\.\d+'
      - 'v\d+\.\d+\.\d+'

jobs:
  push_to_registry_stable:
    name: Push Docker image to Docker Hub (default)
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: |
          echo "##[set-output name=branch;]$([[ $GITHUB_REF == refs/heads/v* ]] && echo ${GITHUB_REF#refs/heads/v} || echo 'stable')"
        id: extract_branch

      - name: Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          tags: |
            coderockr/node-for-build:${{ steps.extract_branch.outputs.branch }}

  push_to_registry_slim:
    name: Push Docker image to Docker Hub (slim)
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: |
          echo "##[set-output name=branch;]$([[ $GITHUB_REF == refs/heads/v* ]] && echo ${GITHUB_REF#refs/heads/v} || echo 'stable')"
        id: extract_branch

      - name: Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.slim
          push: true
          tags: |
            coderockr/node-for-build:${{ steps.extract_branch.outputs.branch }}-slim
